// <auto-generated />
namespace EventBooking.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Lund : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lund));
        
        string IMigrationMetadata.Id
        {
            get { return "201304031519553_Lund"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
